spring:
  profiles:
    active:
    - dev
  mvc:
    favicon:  
      enabled: false
    view:
      prefix: classpath*:/templates/
      suffix: .html
    static-path-pattern: /static/**
  servlet:
  #图片上传配置
    multipart:
      max-file-size: 500kb
      max-request-size: 500kb
           
  #静态html热部署
  thymeleaf:
    cache: false
  cache:
    type: redis  
  redis:
    database: 0
    password: 123456
  #json时间    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


mybatis:
  mapper-locations:
  - classpath*:mapper/*.xml
  type-aliases-package: com.lenovo.bootstrap.mapper
  
  
logging:
  config: classpath:logback-spring.xml  
  level:   
    com.lenovo.bootstrap.mapper: debug 
    com.lenovo.bootstrap.controller: debug
    com.lenovo.bootstrap.service: debug
    org.springframework: debug
    